### ISSUE TITLE
[Bug]: GetBlobStatus should use dialOptions provided from the disperserClient config

### ISSUE THREAD

**Issue by NicolasRampoldi** [Layr-Labs/eigenda#538]
### What happened + What you expected to happen

When setting up the disperser client, I used the following config:
```golang
disp := clients.NewDisperserClient(&clients.Config{
		Hostname:          "disperser-holesky.eigenda.xyz",
		Port:              "443",
		Timeout:           10 * time.Second,
		UseSecureGrpcFlag: true,
	}, signer)
```
Then, I called DisperseBlob:
```golang
blobStatus1, key1, err := disp.DisperseBlob(ctx, paddedData, []uint8{})
```
And I had no problem because the DisperseBlob method adds the dial options to the grpc call:
```golang
dialOptions := c.getDialOptions()
conn, err := grpc.Dial(addr, dialOptions...)
```
But then, when I wanted to run GetBlobStatus: 
```golang
reply1, err = disp.GetBlobStatus(context.Background(), key1)
```

I get:
```
panic: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: http2: frame too large"
```
Because the grpc call is insecure by default in the GetBlobStatus:
```golang
conn, err := grpc.Dial(
		addr,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
	)
```
To fix this, GetBlobStatus should use the dialOptions provided by the config in the disperserClient.

### Versions / Dependencies

- EigenDA: v0.6.2
- Golang: v1.22.0
- OS: macOS Sonoma 14.4.1
- MacBook Air M2, 2022.

### How to reproduce

Set up a disperserClient with the following config:
```golang
disp := clients.NewDisperserClient(&clients.Config{
		Hostname:          "disperser-holesky.eigenda.xyz",
		Port:              "443",
		Timeout:           10 * time.Second,
		UseSecureGrpcFlag: true,
	}, signer)
```
Call GetBlobStatus:
```golang
reply1, err = disp.GetBlobStatus(context.Background(), key1)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ian-shim** [comment]
Thanks for submitting this ticket. Fix is underway

**Comment by ian-shim** [comment]
This should have been resolved. Please reopen the issue if it continues
